hist(ASQ_cleaned$interview_date, breaks = 10)
table(ASQ_cleaned$interview_type)
table(ASQ_cleaned$age_form)
table(ASQ_cleaned$c1)
table(ASQ_cleaned$c1_mc)
table(ASQ_cleaned$c2_mc)
table(ASQ_cleaned$c3_mc)
table(ASQ_cleaned$c4_mc)
table(ASQ_cleaned$c5_mc)
table(ASQ_cleaned$c6_explain)
table(ASQ_cleaned$gm1)
table(ASQ_cleaned$gm2)
table(ASQ_cleaned$gm3)
table(ASQ_cleaned$gm4)
table(ASQ_cleaned$gm5)
table(ASQ_cleaned$gm6)
table(ASQ_cleaned$fm1)
table(ASQ_cleaned$fm2)
table(ASQ_cleaned$fm3)
table(ASQ_cleaned$fm4)
table(ASQ_cleaned$fm5)
table(ASQ_cleaned$fm6)
table(ASQ_cleaned$ps1_mc)
table(ASQ_cleaned$ps3_mc)
table(ASQ_cleaned$ps4_mc)
table(ASQ_cleaned$ps6_mc)

table(ASQ_cleaned$pers1)
table(ASQ_cleaned$pers2)
table(ASQ_cleaned$pers3)
table(ASQ_cleaned$pers4)
table(ASQ_cleaned$pers5)
table(ASQ_cleaned$pers6)
table(ASQ_cleaned$pers2_mc)

table(ASQ_cleaned$o1)
table(ASQ_cleaned$o2)
table(ASQ_cleaned$o3)
table(ASQ_cleaned$o4)
table(ASQ_cleaned$o5)
table(ASQ_cleaned$o6)

unique(ASQ_cleaned$o1_explain)
unique(ASQ_cleaned$o2_explain)
unique(ASQ_cleaned$o3_explain)
unique(ASQ_cleaned$o4_explain)
unique(ASQ_cleaned$o5_explain)
unique(ASQ_cleaned$o6_explain)
